//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5420.
// 
#pragma warning disable 1591

namespace CODConsumer.InsertEntityReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InsertServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class InsertService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InsertService() {
            this.Url = "http://192.168.1.232:1100/EntityDirectory/EntityDirectory/InsertService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateNewOrganization", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateNewOrganization(string RequestedId, string RequestedSoftware, string SoftwareUniqueId, string RequestBy, string EntityId, string Name, string eTin, string EntityOriginator, string LegalStatus, string TradeName, string IncorporationNumber) {
            object[] results = this.Invoke("CreateNewOrganization", new object[] {
                        RequestedId,
                        RequestedSoftware,
                        SoftwareUniqueId,
                        RequestBy,
                        EntityId,
                        Name,
                        eTin,
                        EntityOriginator,
                        LegalStatus,
                        TradeName,
                        IncorporationNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateNewOrganization(string RequestedId, string RequestedSoftware, string SoftwareUniqueId, string RequestBy, string EntityId, string Name, string eTin, string EntityOriginator, string LegalStatus, string TradeName, string IncorporationNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateNewOrganization", new object[] {
                        RequestedId,
                        RequestedSoftware,
                        SoftwareUniqueId,
                        RequestBy,
                        EntityId,
                        Name,
                        eTin,
                        EntityOriginator,
                        LegalStatus,
                        TradeName,
                        IncorporationNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateNewOrganization(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateNewIndividual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateNewIndividual(string RequestedId, string RequestedSoftware, string SoftwareUniqueId, string RequestBy, string EntityId, string Name, string eTin, string EntityOriginator, string FatherName, string MotherName, string DateOfBirth, string BirthCertificateNumber, string Nid, string PassportNumber, string DrivingLicenseNumber) {
            object[] results = this.Invoke("CreateNewIndividual", new object[] {
                        RequestedId,
                        RequestedSoftware,
                        SoftwareUniqueId,
                        RequestBy,
                        EntityId,
                        Name,
                        eTin,
                        EntityOriginator,
                        FatherName,
                        MotherName,
                        DateOfBirth,
                        BirthCertificateNumber,
                        Nid,
                        PassportNumber,
                        DrivingLicenseNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateNewIndividual(
                    string RequestedId, 
                    string RequestedSoftware, 
                    string SoftwareUniqueId, 
                    string RequestBy, 
                    string EntityId, 
                    string Name, 
                    string eTin, 
                    string EntityOriginator, 
                    string FatherName, 
                    string MotherName, 
                    string DateOfBirth, 
                    string BirthCertificateNumber, 
                    string Nid, 
                    string PassportNumber, 
                    string DrivingLicenseNumber, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("CreateNewIndividual", new object[] {
                        RequestedId,
                        RequestedSoftware,
                        SoftwareUniqueId,
                        RequestBy,
                        EntityId,
                        Name,
                        eTin,
                        EntityOriginator,
                        FatherName,
                        MotherName,
                        DateOfBirth,
                        BirthCertificateNumber,
                        Nid,
                        PassportNumber,
                        DrivingLicenseNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateNewIndividual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchEntity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Entities[] SearchEntity(string EntityId, string EntityType, string Name, string eTin) {
            object[] results = this.Invoke("SearchEntity", new object[] {
                        EntityId,
                        EntityType,
                        Name,
                        eTin});
            return ((Entities[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchEntity(string EntityId, string EntityType, string Name, string eTin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchEntity", new object[] {
                        EntityId,
                        EntityType,
                        Name,
                        eTin}, callback, asyncState);
        }
        
        /// <remarks/>
        public Entities[] EndSearchEntity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Entities[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchOrganization", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Organization[] SearchOrganization(string Name, string EntityId, string TradeName, string eTin, string IncorporationNumber) {
            object[] results = this.Invoke("SearchOrganization", new object[] {
                        Name,
                        EntityId,
                        TradeName,
                        eTin,
                        IncorporationNumber});
            return ((Organization[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchOrganization(string Name, string EntityId, string TradeName, string eTin, string IncorporationNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchOrganization", new object[] {
                        Name,
                        EntityId,
                        TradeName,
                        eTin,
                        IncorporationNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public Organization[] EndSearchOrganization(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Organization[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchIndividual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Individual[] SearchIndividual(string Name, string EntityId, string BirthCertificateNumber, string Nid, string PassportNumber, string eTin, string DrivingLicenseNumber) {
            object[] results = this.Invoke("SearchIndividual", new object[] {
                        Name,
                        EntityId,
                        BirthCertificateNumber,
                        Nid,
                        PassportNumber,
                        eTin,
                        DrivingLicenseNumber});
            return ((Individual[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchIndividual(string Name, string EntityId, string BirthCertificateNumber, string Nid, string PassportNumber, string eTin, string DrivingLicenseNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchIndividual", new object[] {
                        Name,
                        EntityId,
                        BirthCertificateNumber,
                        Nid,
                        PassportNumber,
                        eTin,
                        DrivingLicenseNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public Individual[] EndSearchIndividual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Individual[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertEntityAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertEntityAddress(string RequestId, int AddressTypeId, int DivisionId, int DistrictId, int ThanaId, string PostOfficeId, string AddressDetails) {
            object[] results = this.Invoke("InsertEntityAddress", new object[] {
                        RequestId,
                        AddressTypeId,
                        DivisionId,
                        DistrictId,
                        ThanaId,
                        PostOfficeId,
                        AddressDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertEntityAddress(string RequestId, int AddressTypeId, int DivisionId, int DistrictId, int ThanaId, string PostOfficeId, string AddressDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertEntityAddress", new object[] {
                        RequestId,
                        AddressTypeId,
                        DivisionId,
                        DistrictId,
                        ThanaId,
                        PostOfficeId,
                        AddressDetails}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertEntityAddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertEntityDocument", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertEntityDocument(string RequestId, string ReferenceType, System.DateTime DocumentApprovalDate, short DocumentTypeId, string DocumentTitle, string DocumentPath, string RequestBy) {
            object[] results = this.Invoke("InsertEntityDocument", new object[] {
                        RequestId,
                        ReferenceType,
                        DocumentApprovalDate,
                        DocumentTypeId,
                        DocumentTitle,
                        DocumentPath,
                        RequestBy});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertEntityDocument(string RequestId, string ReferenceType, System.DateTime DocumentApprovalDate, short DocumentTypeId, string DocumentTitle, string DocumentPath, string RequestBy, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertEntityDocument", new object[] {
                        RequestId,
                        ReferenceType,
                        DocumentApprovalDate,
                        DocumentTypeId,
                        DocumentTitle,
                        DocumentPath,
                        RequestBy}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertEntityDocument(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Individual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entities : BaseModel {
        
        private string entityIdField;
        
        private string entityTypeField;
        
        private string nameField;
        
        private string eTinField;
        
        private string entityOriginatorField;
        
        private Address[] addressListField;
        
        private Document[] documentListField;
        
        /// <remarks/>
        public string EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string eTin {
            get {
                return this.eTinField;
            }
            set {
                this.eTinField = value;
            }
        }
        
        /// <remarks/>
        public string EntityOriginator {
            get {
                return this.entityOriginatorField;
            }
            set {
                this.entityOriginatorField = value;
            }
        }
        
        /// <remarks/>
        public Address[] AddressList {
            get {
                return this.addressListField;
            }
            set {
                this.addressListField = value;
            }
        }
        
        /// <remarks/>
        public Document[] DocumentList {
            get {
                return this.documentListField;
            }
            set {
                this.documentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Address : AddressTypes {
        
        private string addressIdField;
        
        private string entityIdField;
        
        private int serialNoField;
        
        private int countryIdField;
        
        private string countryNameField;
        
        private int divisionIdField;
        
        private string divisionNameField;
        
        private int districtIdField;
        
        private string districtNameField;
        
        private int thanaIdField;
        
        private string thanaNameField;
        
        private System.Nullable<int> postOfficeIdField;
        
        private string postOfficeNameField;
        
        private string postCodeField;
        
        private string addressDetailsField;
        
        /// <remarks/>
        public string AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        public string EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        public int SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public int DivisionId {
            get {
                return this.divisionIdField;
            }
            set {
                this.divisionIdField = value;
            }
        }
        
        /// <remarks/>
        public string DivisionName {
            get {
                return this.divisionNameField;
            }
            set {
                this.divisionNameField = value;
            }
        }
        
        /// <remarks/>
        public int DistrictId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
            }
        }
        
        /// <remarks/>
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        public int ThanaId {
            get {
                return this.thanaIdField;
            }
            set {
                this.thanaIdField = value;
            }
        }
        
        /// <remarks/>
        public string ThanaName {
            get {
                return this.thanaNameField;
            }
            set {
                this.thanaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PostOfficeId {
            get {
                return this.postOfficeIdField;
            }
            set {
                this.postOfficeIdField = value;
            }
        }
        
        /// <remarks/>
        public string PostOfficeName {
            get {
                return this.postOfficeNameField;
            }
            set {
                this.postOfficeNameField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AddressDetails {
            get {
                return this.addressDetailsField;
            }
            set {
                this.addressDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddressTypes : BaseModel {
        
        private int addressTypeIdField;
        
        private string addressTypeNameField;
        
        /// <remarks/>
        public int AddressTypeId {
            get {
                return this.addressTypeIdField;
            }
            set {
                this.addressTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string AddressTypeName {
            get {
                return this.addressTypeNameField;
            }
            set {
                this.addressTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressTypes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entities))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Individual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseModel {
        
        private bool isNewField;
        
        private bool isDirtyField;
        
        private bool isDeleteField;
        
        private string statusField;
        
        private System.DateTime systemDateField;
        
        private System.DateTime createDateField;
        
        private string requestByField;
        
        private string requestNameField;
        
        private System.DateTime requestDateField;
        
        private string checkByField;
        
        private System.Nullable<System.DateTime> checkDateField;
        
        private string remarkField;
        
        /// <remarks/>
        public bool IsNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDirty {
            get {
                return this.isDirtyField;
            }
            set {
                this.isDirtyField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDelete {
            get {
                return this.isDeleteField;
            }
            set {
                this.isDeleteField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SystemDate {
            get {
                return this.systemDateField;
            }
            set {
                this.systemDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string RequestBy {
            get {
                return this.requestByField;
            }
            set {
                this.requestByField = value;
            }
        }
        
        /// <remarks/>
        public string RequestName {
            get {
                return this.requestNameField;
            }
            set {
                this.requestNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public string CheckBy {
            get {
                return this.checkByField;
            }
            set {
                this.checkByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CheckDate {
            get {
                return this.checkDateField;
            }
            set {
                this.checkDateField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Document : BaseModel {
        
        private System.Guid documentIdField;
        
        private int documentSerialField;
        
        private string referenceIdField;
        
        private string referenceTypeField;
        
        private System.DateTime documentApprovalDateField;
        
        private short documentTypeIdField;
        
        private string documentTypeName_VWField;
        
        private string documentTitleField;
        
        private string documentPathField;
        
        /// <remarks/>
        public System.Guid DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentSerial {
            get {
                return this.documentSerialField;
            }
            set {
                this.documentSerialField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DocumentApprovalDate {
            get {
                return this.documentApprovalDateField;
            }
            set {
                this.documentApprovalDateField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentTypeName_VW {
            get {
                return this.documentTypeName_VWField;
            }
            set {
                this.documentTypeName_VWField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentTitle {
            get {
                return this.documentTitleField;
            }
            set {
                this.documentTitleField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentPath {
            get {
                return this.documentPathField;
            }
            set {
                this.documentPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Individual : Entities {
        
        private string fatherNameField;
        
        private string motherNameField;
        
        private System.DateTime dateOfBirthField;
        
        private string birthCertificateNumberField;
        
        private string nidField;
        
        private string passportNumberField;
        
        private string drivingLicenseNumberField;
        
        /// <remarks/>
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        public string MotherName {
            get {
                return this.motherNameField;
            }
            set {
                this.motherNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string BirthCertificateNumber {
            get {
                return this.birthCertificateNumberField;
            }
            set {
                this.birthCertificateNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Nid {
            get {
                return this.nidField;
            }
            set {
                this.nidField = value;
            }
        }
        
        /// <remarks/>
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DrivingLicenseNumber {
            get {
                return this.drivingLicenseNumberField;
            }
            set {
                this.drivingLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Organization : Entities {
        
        private string legalStatusField;
        
        private string legalStatusNameField;
        
        private string tradeNameField;
        
        private string incorporationNumberField;
        
        /// <remarks/>
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusName {
            get {
                return this.legalStatusNameField;
            }
            set {
                this.legalStatusNameField = value;
            }
        }
        
        /// <remarks/>
        public string TradeName {
            get {
                return this.tradeNameField;
            }
            set {
                this.tradeNameField = value;
            }
        }
        
        /// <remarks/>
        public string IncorporationNumber {
            get {
                return this.incorporationNumberField;
            }
            set {
                this.incorporationNumberField = value;
            }
        }
    }
}

#pragma warning restore 1591